apiVersion: apps/v1
kind: Deployment
metadata:
  name: paiements-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpaiements
  template:
    metadata:
      labels:
        app: mpaiements
    spec:
      containers:
      - name: mpaiements
        image: elganiesta/mpaiements:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9003
---
apiVersion: v1
kind: Service
metadata:
  name: mpaiements-service
spec:
  selector:
    app: mpaiements
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9003
